question_data = [
     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "The ARM computer chip was originally developed by Acorn Computers.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "The HTML5 standard was published in 2014.", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "A Boolean value of &quot;0&quot; represents which of these words?",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "There is only 1 root name server, among 13 in total, that is currently located in Asia.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "The first dual-core CPU was the Intel Pentium D.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "The &#039;Raspberry Pi&#039; series of single-board computers were created in the United States.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]}
                                     ]
